name: Publish Python ðŸ distribution ðŸ“¦ to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish-to-pypi:
    name: Teleport Python ðŸ Distribution ðŸ“¦ to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/asgi-request-duration
    permissions:
      id-token: write

    steps:
    - name: Summon the Distribution Artifacts ðŸ§™â€â™‚ï¸
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Cast the Publish Spell ðŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70

  github-release:
    name: Enchant the Python ðŸ Distribution ðŸ“¦ with Sigstore and Upload to GitHub Release
    needs: publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: Summon the Distribution Artifacts ðŸ§™â€â™‚ï¸
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Enchant the Artifacts with Sigstore âœ¨
      uses: sigstore/gh-action-sigstore-python@f514d46b907ebcd5bedc05145c03b69c1edd8b46
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create the GitHub Release ðŸŽ‰
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" --notes "" 
    - name: Upload the Enchanted Artifacts to GitHub Release ðŸ§³
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload "$GITHUB_REF_NAME" dist/** --repo "$GITHUB_REPOSITORY"